name: quran_app
description: "Quran app using flutter (Basic)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  quran_flutter: ^1.0.3
  http: ^1.3.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/quranjson/source/surah/
    - assets/fonts/Amiri/Amiri-Regular.ttf
    - assets/fonts/Amiri/Amiri-Bold.ttf
    - assets/images/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
          weight: 700

    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/Amiri_Quran/AmiriQuran-Regular.ttf
